version: "3.4"

services:
  db:
    image: postgres:11.2
    environment: &postgres_envs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: scholarly-content-detail-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - "../:/srv/app/"
    environment:
      <<: *postgres_envs
      WAIT_HOSTS: db:5432
    depends_on:
      - db
    ports:
      - "5000:5000"
