version: "3.4"

services:
  app-tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    working_dir: /srv/app
    volumes:
      - ../:/srv/app
    command: pytest -v
