version: "3.4"

services:
  db:
    image: postgres:11.2
    environment: &postgres_envs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: scholarly-content-detail-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    command: /bin/bash -c "/wait && flask run --host=0.0.0.0"
    working_dir: /srv/app/
    volumes:
      - ../:/srv/app/
    environment:
      <<: *postgres_envs
      WAIT_HOSTS: db:5432
      FLASK_APP: scholarly_content_detail:create_app('dev.py')
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/5000'"]
      interval: 5s
    depends_on:
      - db
    ports:
      - "5000:5000"
